/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TargetDel struct for TargetDel
type TargetDel struct {
	TargetDeletionConsumed bool `json:"target_deletion_consumed,omitempty"`
	TargetDeletionAllowance int64 `json:"target_deletion_allowance,omitempty"`
}
