/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanAppWvs struct for ScanAppWvs
type ScanAppWvs struct {
	Status string `json:"status,omitempty"`
	AbortRequested bool `json:"abort_requested,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	EndDeadline string `json:"end_deadline,omitempty"`
	EventLevel string `json:"event_level,omitempty"`
	// key is target uuid
	Hosts map[string]ScanAppHost `json:"hosts,omitempty"`
	Main ScanAppWvsMain `json:"main,omitempty"`
}
