/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TargetConfigProxy struct for TargetConfigProxy
type TargetConfigProxy struct {
	Enable bool `json:"enable,omitempty"`
	Address string `json:"address,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Port int64 `json:"port,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}
