/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanDetailCurrentSession struct for ScanDetailCurrentSession
type ScanDetailCurrentSession struct {
	EventLevel int64 `json:"event_level,omitempty"`
	Progress string `json:"progress,omitempty"`
	ScanSessionId string `json:"scan_session_id,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	Status string `json:"status,omitempty"`
	Threat int64 `json:"threat,omitempty"`
}
