/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TargetConfig struct for TargetConfig
type TargetConfig struct {
	Authentication TargetConfigAuthentication `json:"authentication,omitempty"`
	CaseSensitive string `json:"case_sensitive,omitempty"`
	ClientCertificatePassword string `json:"client_certificate_password,omitempty"`
	CustomCookies []TargetConfigCustomCookies `json:"custom_cookies,omitempty"`
	// MyHeader:myheadervalue
	CustomHeaders []string `json:"custom_headers,omitempty"`
	ExcludedHoursId string `json:"excluded_hours_id,omitempty"`
	Debug bool `json:"debug,omitempty"`
	Login TargetConfigLogin `json:"login,omitempty"`
	ExcludedPaths []string `json:"excluded_paths,omitempty"`
	ScanSpeed string `json:"scan_speed,omitempty"`
	Technologies []string `json:"technologies,omitempty"`
	UserAgent string `json:"user_agent,omitempty"`
	Sensor bool `json:"sensor,omitempty"`
	SensorSecret string `json:"sensor_secret,omitempty"`
	LimitCrawlerScope bool `json:"limit_crawler_scope,omitempty"`
	SshCredentials TargetConfigSshCredentials `json:"ssh_credentials,omitempty"`
	Proxy TargetConfigProxy `json:"proxy,omitempty"`
}
