/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanAppWvsMain struct for ScanAppWvsMain
type ScanAppWvsMain struct {
	WebScanStatus ScanAppWvsMainStatus `json:"web_scan_status,omitempty"`
	Progress int64 `json:"progress,omitempty"`
	Duration int64 `json:"duration,omitempty"`
	Status string `json:"status,omitempty"`
	Vulns []ScanAppVuln `json:"vulns,omitempty"`
	Messages []ScanAppMessage `json:"messages,omitempty"`
}
