/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ScanDetailCurrentSession struct for ScanDetailCurrentSession
type ScanDetailCurrentSession struct {
	EventLevel    int64  `json:"event_level,omitempty"`
	Progress      int64  `json:"progress,omitempty"`
	ScanSessionId string `json:"scan_session_id,omitempty"`
	StartDate     string `json:"start_date,omitempty"`

	/*
	   Enum:
	   Array [10]
	   0: "scheduled"
	   1: "queued"
	   2: "starting"
	   3: "processing"
	   4: "aborting"
	   5: "aborted"
	   6: "pausing"
	   7: "paused"
	   8: "completed"
	   9: "failed"
	*/

	Status string `json:"status,omitempty"`
	Threat int64  `json:"threat,omitempty"`
}
