/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanStatServerityCounts struct for ScanStatServerityCounts
type ScanStatServerityCounts struct {
	High int64 `json:"high,omitempty"`
	Medium int64 `json:"medium,omitempty"`
	Low int64 `json:"low,omitempty"`
}
