/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Scan struct for Scan
type Scan struct {
	TargetId    string   `json:"target_id"`
	ProfileId   string   `json:"profile_id"`
	UiSessionid string   `json:"ui_sessionid,omitempty"`
	Schedule    Schedual `json:"schedule"`
}
